### ISSUE TITLE
OIDCUserInfoRefreshInterval does not redirect to authentication page if token is invalid

### ISSUE THREAD

**Issue by kerrermanisNL** [pingidentity/mod_auth_openidc#194] opened 2016-11-09 14:48 UTC
Consider the following:
There is an OP that you can log into. This OP provides tokens for clients that connect to it using openID. The clients have the `OIDCUserInfoRefreshInterval` setting set to `x` seconds. Every `x` seconds the client(s) request the user information again from the OP. When a token for a certain user is revoked by the OP, the client requesting the user information gets a 401 response.

I would expect the user to be logged out and be redirected to the OP login page, because the (correct token) information can't be retrieved for the user. Instead the user is kept logged in.

Am I missing another setting, or is this actually a bug in the system? Should we go about this issue some different way? What is the use of the `OIDCUserInfoRefreshInterval` setting if a 401 response keeps the user logged in? We don't want to manually remove sessions from mod_auth_openidc for every client that's connected to our OP when we receive a 401 for that user. Any feedback considering this issue would be greatly appreciated :)

**Comment by zandbelt** [comment] 2016-11-09 15:00
Protocol-wise and technically the information returned from the user endpoint does not authenticate the user, that is what the id_token is for, it merely provides extra claims about the user. 

I do agree that your proposal makes sense to implement as configurable behaviour, perhaps even the default.

**Comment by zandbelt** [comment] 2016-11-09 15:04
You should be able to use the refresh token to get a new access token.

**Comment by kerrermanisNL** [comment] 2016-11-09 15:18
Hey Hans, thanks for your response. In our case we don't want to refresh the token for the user, but keep him logged out. For example we've determined that a user is being naughty and disabled his account.

We've tried solving this with a max session duration. After the session is expired a new request is made to the OP. If the OP has revoked the token the user will be redirected to the login page, otherwise the user will be able to continue where he was. This however messes with some of our (AJAX) forms. If a user submits a form after the session has expired the POST data will be lost since the client will first have to perform a request to the OP.

Do you have any suggestions on how to solve this problem, or is using the `OIDCUserInfoRefreshInterval` a correct solution for this? We're aware of the `OIDCUnAuthAction`, but don't think this solves our issue.

I actually just noticed the `OIDCPreservePost` setting just now. I don't think that was there a month ago? Perhaps this could be the answer to our problems.

**Comment by zandbelt** [comment] 2016-11-09 16:02
Going back to the OP is indeed how this is supposed to work from a standard/protocol viewpoint. I appreciate that that may sometimes be problematic in real (web) life, e.g. with POST data. `OIDCPreservePost` was meant to solve that but for webforms rather than AJAX calls; it produces Javascript that the browser interprets to store form data in HTML 5 local storage. That is something your AJAX client would not do.

Even though at some point someone (or me) may implement the `OIDCUserInfoRefreshInterval` it is not really meant to be used to logout users so it is a bit of a twist, but a perhaps a useful twist.

Is there any chance you can leverage some client side framework/functionality to temporarily store the POST data or regenerate it?

**Comment by zandbelt** [comment] 2016-11-09 16:23
Thinking a bit more about this: I believe your point is not sending the user back to the OP - because he shouldn't be able to login anymore anyhow, right?

So what about this:

When setting a `Require claim` directive on your paths to require a claim that is returned only from the userinfo endpoint (i.e. not in the `id_token` I believe you achieve your goal: users won't be able to access your protected content when that claim could not be retrieved from the userinfo endpoint somehow. Their authenticated session (cookie) would still exist but they just wouldn't be entitled to access any path/content. They would not be sent back to the OP, but I believe that is not really what you are looking for anyway, if I understand you correctly? 

I do see that I need to apply a fix in that case since currently the original claims would be preserved when no new ones could be obtained. That I would consider a bugfix because the `OIDCUserInfoRefreshInterval`  setting implies that the latest data should be required and authorization decisions should not rely on stale data.

**Comment by kerrermanisNL** [comment] 2016-11-09 16:41
Hmm, no, sending the user back to the OP would not be a strict requirement. You're correct that the user should not be able to login anymore in any case.

I think your solution could work indeed. I'll have a look tomorrow to see how I can implement this. I'll let you know how that goes :)

**Comment by zandbelt** [comment] 2016-11-09 17:24
I worked on a fix already; will checkin asap

**Comment by zandbelt** [comment] 2016-11-09 18:12
348f282 addresses this; it will also keep respecting `OIDCUserInfoRefreshInterval` after a failure so when the user is "enabled" again (or the server is back up after a failure/restart) users would be able to continue their session; if you can confirm the working I'll release 2.1.1

**Comment by gertjanol** [comment] 2016-11-10 09:48
:clap: @zandbelt 
Thank you for thinking along with us on this issue!

**Comment by zandbelt** [comment] 2016-11-10 18:23
I've tested/confirmed and released 2.1.1 that includes that fix. Closing the ticket now. If you do have feedback please add it here. If the problem persists or a related issue occurs you can always reopen.

**Closed by zandbelt** 2016-11-10 18:23 UTC
Labels: bug, enhancement

**Comment by kerrermanisNL** [comment] 2016-11-17 10:41
Thanks for your great support Zandbelt :)
