### ISSUE TITLE
Encounter "Internal Server Error" sometimes when user re-login the site after a period of time

### ISSUE THREAD

**Issue by zyjibmcn** [pingidentity/mod_auth_openidc#214] opened 2017-01-24 15:32 UTC
We have configured the mod_auth_openidc successfully. Most of time, it worked properly.

But sometimes when users re-login the site after a period of time, they got the "Internal Server Error"(HTTP 500). Only clear the browser cache can resolve the issue. Any idea?

I attached the access.log and error.log related to the request lead to problem.
[hotfix.zip](https://github.com/pingidentity/mod_auth_openidc/files/727097/hotfix.zip)

**Comment by zandbelt** [comment] 2017-01-24 16:27
It seems that you are hitting the redirect URI with an invalid request because you used the "browser back" button. That is not an error but expected behaviour. From the logs it doesn't look like re-login is happening.

**Comment by zyjibmcn** [comment] 2017-01-25 02:22
Thanks for your answer. But "browser back" is not the major reason. We also saw the error occurred when there was no "browser back" from user. 
When I say "re-login", I just mean user open the application again after days.

The most strange thing is once they hit the "Internal Server Error", they will always be directed to the "Internal Server Error" page until they clearing the browser cache. So the usability is bad for our application now.

**Comment by zandbelt** [comment] 2017-01-25 04:35
Can you provide logs with `LogLevel` set to `debug`, the version of mod_auth_openidc that you are using and the platform that you're on?

**Comment by zyjibmcn** [comment] 2017-01-26 05:50
@zandbelt I have attached the apache access/error logs with LogLeve set to debug. The access log and error log are closely related. The error happened at 09:37:30. 

I basically used the mod_auth_openidc v1.8.10(I built the binary from commit bfc19a9365dc06942edfe37020d2fca98ec4ef22). 

[apache_debug_logs.zip](https://github.com/pingidentity/mod_auth_openidc/files/731618/apache_debug_logs.zip)

```
$ uname -a
Linux servername 3.10.0-327.36.3.el7.s390x #1 SMP Thu Oct 20 04:58:05 EDT 2016 s390x s390x s390x GNU/Linux

$ /usr/sbin/httpd -version
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
```
[Uploading apache_debug_logs.zip…]()

**Comment by zandbelt** [comment] 2017-01-26 12:02
Please use the latest release.

**Comment by zyjibmcn** [comment] 2017-01-26 14:27
Thanks. I will try to use a latest version. 
But any findings from my debug logs, doesn't that relate to an known issue of old release?

 I first tried mod_auth_openidc at July last year, so I used most recent version at that moment, and haven't updated from then. Now we suffer from this issue frequently at present.

**Comment by zandbelt** [comment] 2017-01-26 14:48
The logs actually show the following: the user is redirected away to the Provider at a certain timestamp (09:37:30) but then only returns with an authentication response 25 minutes later (10:03:43). By that time the request state has timed out and an error is thrown, which is expected behaviour.

**Comment by zandbelt** [comment] 2017-01-30 20:15
Any update on this?

**Comment by zyjibmcn** [comment] 2017-02-08 09:23
@zandbelt Sorry, I wasn't able to update the status due to the Chinese Spring Festival Holiday. I think I may have chosen a bad case before.  Our OIDC provider would not respond so slowly. I think the default value(300s) for OIDCStateTimeout is suitable while larger value may not acceptable for us.

I attached a new package of debug logs.  The error happened around 18/Jan/2017:20:53:57, the user consistently got the HTTP 500 error until I asked him to clear the browser cache and tried again. 
`
[apache_debug_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/760153/apache_debug_log.zip)

[Wed Jan 18 20:59:53.054535 2017] [auth_openidc:error] [pid 46404] [client 9.78.170.160:63761] oidc_unsolicited_proto_state: **could not parse JWT from state: invalid unsolicited response:** [src/jose/apr_jwt.c:180: apr_jwt_base64url_decode_object]: JSON parsing (json_loads) failed: unable to decode byte 0xd0 (\xd0\xd85;\xdb5\xbcQ\xfc4\xf1$\xb3\x05h#\x06\x98\x81V)\n, referer: https://hostname/redirect
`
Could you please look into the new debug logs? thanks.

Does the Basic flow (OIDCResponseType code) can reduce the network traffics and improve the response time except avoid long URL problem? I didn't see any of these benefits by manual testing. Thanks.

**Comment by zandbelt** [comment] 2017-02-08 11:06
The last log is not produced using `LogLevel debug`, it shows only repeated errors with no context.

**Comment by zyjibmcn** [comment] 2017-02-08 13:05
Sorry for that, I just attached new logs, thanks.


[apache_debug_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/760662/apache_debug_log.zip)

The error message in it as follows:
[Thu Feb 02 07:28:37.267194 2017] [auth_openidc:error] [pid 38422] [client 9.63.21.97:51554] oidc_unsolicited_proto_state: could not parse JWT from state: invalid unsolicited response: [src/jose/apr_jwt.c:180: apr_jwt_base64url_decode_object]: JSON parsing (json_loads) failed: unable to decode byte 0xe2 (\xe2_\x01\xce\x9e\x7fim5\xa5r'\xf7\xb9\v\xe7-7\x13\x16)\n, referer: https://hostname/redirect

**Comment by zandbelt** [comment] 2017-02-08 19:55
I would advise you to use the latest release 2.1.5 and to avoid using anything other than `OIDCResponceType code` because of security and URL size restrictions. Only if the problem still exists then I can try and reproduce and fix.

**Comment by zyjibmcn** [comment] 2017-02-09 02:14
OK, thanks, I will following you suggestion to upgrade the module and use code flow. I will give my update later(maybe two or three days for observation).

**Comment by zyjibmcn** [comment] 2017-02-15 03:10
@zandbelt I updated the module to 2.1.5 and used **OIDCResponseType code**, the problem haven't occurred for two days. I will close the issue if the problem cannot be reproduced by end of this week.
thanks again.

**Comment by zandbelt** [comment] 2017-02-15 06:34
Ok, I'm closing it then; you can re-open when needed.

**Closed by zandbelt** 2017-02-15 06:34 UTC
Labels: invalid
