### ISSUE TITLE
User gets 500 error when going back after login

### ISSUE THREAD

**Issue by mvschaik** [pingidentity/mod_auth_openidc#89] opened 2015-08-12 11:43 UTC
If a user clicks on the browser "Back" button after a successful login, a 500 error is generated.

So, user accesses a protected URL, is redirected by mod_auth_openidc to the auth server, is redirected back after login and consent, and redirected to the page he wanted to access.
When the user clicks the "back" button the browser navigates to `[RedirectURI]?state=v-xV-2ZfVF4xhpD07ku0Fumieb8&code=136211cb33e443038649ccbf9fb5807e` and sees a 500 error screen. Apache generates the following logs:

```
oidc_restore_proto_state: no "mod_auth_openidc_state_v-xV-2ZfVF4xhpD07ku0Fumieb8" state cookie found
oidc_unsolicited_proto_state: could not parse JWT from state: invalid unsolicited response: [src/jose/apr_jwt.c:177: apr_jwt_base64url_decode_object]: JSON parsing (json_loads) failed: unable to decode byte 0xbf (\xbf\xecU\xfbf_T^1\x86\x90\xf4\xeeK\xb4\x16\xe9\xa2y\xbf)\n
oidc_authorization_response_match_state: unable to restore state
```

**Comment by zandbelt** [comment] 2015-08-14 12:25
Hitting the `redirect_uri` again with no associated authentication request (because the state of the previous one has been consumed now) is supposed to return an error. What is the behavior you're looking for?

**Comment by zandbelt** [comment] 2015-08-19 20:26
Do you want to turn it it no a feature request? Otherwise I'll close it since it is expected behavior.

**Comment by mvschaik** [comment] 2015-08-19 20:47
Sorry for the late response!

I agree it is expected behavior, but on the other hand it is undesirable for visitors to get a 500 error.

What actually happens is that on navigating back, the user is first brought back to the login page, since this is the last page he visited. Since he's already logged in, he is immediately granted a new code and redirected back to the `redirect_uri`. This is also expected behavior, but the state is taken from the browser history and is already consumed by mod_auth_openidc as you indicate.

So at this point I'm not sure anymore how to avoid the 500. The auth server is right to give a new token and redirect back to the `redirect_uri`. What else can it do? Keep track and detect it has seen the state before (which seems inappropriate), and instead not redirect but show a custom page, containing what? And on the other hand mod_auth_openidc is right to reject the code & state.

The only thing I can think of right now is to configure a custom 500 page for the redirect_uri that just redirects into the application if the user has a session.

This might be out of scope for mod_auth_openidc, so feel free to close this issue.

**Comment by zandbelt** [comment] 2015-08-19 20:53
Thanks for thinking out loud. I guess detecting this state (sic) and checking for an existing session would be an achievable goal and desirable from a user's point of view. So I'll leave it as a feature request.

**Comment by bertramn** [comment] 2015-08-31 08:13
+1 from me

**Comment by zandbelt** [comment] 2015-09-02 07:02
I can't reproduce this right away. Can you specify in what environment you're encountering this, so version, browser/OS, which provider and which Apache server environment?

**Comment by zandbelt** [comment] 2015-09-04 08:57
please verify c12e3d2 in your environment

**Comment by scottdear** [comment] 2015-09-09 22:38
Hey now, just checkin in on this one.  I get the same error logged, i.e. can't , but I reproduce as follows:

1. Open browser on a an openid protected resouce.
2. Browser gets redircted to my OP login page
3. Wait for 3 or more minutes
4. Finish logging in

When enter my username/password and and enter them, my OP redirects back to the redirect_uri, .../oauth2callback, and at that point I get the 500 server error with what appears to be the same error as above, i.e. unable to restore state.

I am backing my openidc w/ memcache, and I am assuming the memcache entry storing the state is expiring before I finish the login, then when the browser returns, it can't find the previous state.

Is there a more graceful way to handle slowpoke logins?  Is this even the same bug?
```
[Wed Sep 09 15:29:18.092725 2015] [auth_openidc:error] [pid 3802] [client 10.137.54.24:58241] oidc_restore_proto_state: no "mod_auth_openidc_state_xxx" state cookie found, referer: https://login.prospectsforme.com/oidc/login
[Wed Sep 09 15:29:18.092822 2015] [auth_openidc:error] [pid 3802] [client 10.137.54.24:58241] oidc_unsolicited_proto_state: could not parse JWT from state: invalid unsolicited response: [src/jose/apr_jwt.c:173: apr_jwt_base64url_decode_object]: JSON parsing (json_loads) failed: '[' or '{' expected near '\xc2\xa2' (\xc2\xa2\xc8la\x12\xe0\x91W\xaf\x8aj\x928c\xf7\xb0\x91`\b)\n, referer: https://login.prospectsforme.com/oidc/login
[Wed Sep 09 15:29:18.092840 2015] [auth_openidc:error] [pid 3802] [client 10.137.54.24:58241] oidc_authorization_response_match_state: unable to restore state, referer: https://login.prospectsforme.com/oidc/login
```

**Comment by zandbelt** [comment] 2015-09-10 01:41
@scottdear are you saying you experience this behavior with the latest commit? In that case I'd be interested in the browser trace. FYI: until a successful login is established, no backend session state is being maintained i.e. all state is kept in the `state` cookie.  Upon receiving an authorization response, the state in the response is checked against the state stored in the cookie. The latest commit deals with the case when there is no state cookie: then it compares the state against the one stored in the session to allow for a replay.

**Comment by prospectoria** [comment] 2015-09-10 16:44
@zandbelt nope, not the latest commit, and #86 is the exact issue I'm experiencing.  I just saw this one float by and wanted to see if they are related.  I will test w/ the latest commit and make sure OIDCDefaultURL is set,  I'll betcha it resolves my issue.

**Comment by zandbelt** [comment] 2015-09-10 17:23
great, thanks!

**Comment by scottdear** [comment] 2015-09-14 20:58
Alrighty then, I download the latest (I'm also prospectoria BTW [ it's my admin acct ]).  And it does get rid of the 500 error, and instead sends the user to the OIDCDefaultURL.  What I did was the following:  1) Created a custom discovery page using OIDCDiscoverURL.  2) Capture target_link_uri on the custom discovery page in a session variable.  3) Configure OIDCDefaultURL to be a page called "timeout".  4) On timeout (which would previously throw a 500 error), it instead sends them to the "timeout page. 5) The timeout reads the target_link_uri from the session variable set in step 2 and uses it for a "try again" link.  This has the net effect of bouncing them off of the protected resource, then to oauth2callback, then to the login server again with a fresh session, state, etc.

**Comment by zandbelt** [comment] 2015-09-14 21:07
I think this is how it should work for now. It would be more convenient to store the`target_link_uri` as a part of the state parameter value but I still think this is an edge case that can be mitigated by extending the state timeout.

**Closed by zandbelt** 2015-09-14 21:07 UTC
Labels: enhancement

**Comment by mvschaik** [comment] 2015-09-24 14:20
Sorry I didn't have the time to check it out earlier. Works like a charm, thanks!
